# Generated by Django 4.1.2 on 2022-10-17 05:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
