# Generated by Django 4.1.2 on 2022-10-27 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_rename_profile1_membership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
